# -*- coding: utf-8 -*-
"""UCBS-65-AL-03_Cyclic voltammogram calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QymX6VWlooFKRcFbGtykob875XMtFhNs
"""

from matplotlib import font_manager
import matplotlib.pyplot as plt

# Assuming the font file is uploaded to the /content/ directory
font_path = "/Inter-Italic-VariableFont_opsz,wght.ttf"

font_manager.fontManager.addfont(font_path)

font_name = font_manager.FontProperties(fname=font_path).get_name()
plt.rcParams["font.family"] = font_name

print(font_name)

import pandas as pd
from matplotlib import pyplot as plt


# Data from the table
potential = [
    160,150,140,130,120,110,100,90,80,70,
    65,60,55,50,45,40,35,30,25,20,
    15,10,5,0,-5,-10,-15,-20,-25,-30,
    -35,-40,-45,-50,-60,-70,-80,-90,-100
]

data = {
    0.05: [
        0.003,0.003,0.004,0.006,0.009,0.014,0.020,0.029,0.042,0.061,
        0.073,0.086,0.102,0.120,0.140,0.163,0.188,0.216,0.244,0.273,
        0.303,0.333,0.359,0.384,0.405,0.423,0.435,0.444,0.448,0.448,
        0.445,0.439,0.431,0.421,0.399,0.375,0.351,0.330,0.311
    ],
    0.2: [
        0.003,0.003,0.005,0.007,0.010,0.015,0.021,0.031,0.045,0.065,
        0.077,0.092,0.108,0.128,0.148,0.172,0.199,0.227,0.256,0.288,
        0.317,0.347,0.374,0.398,0.418,0.434,0.445,0.452,0.454,0.452,
        0.448,0.440,0.430,0.419,0.395,0.369,0.346,0.325,0.305
    ],
    0.5: [
        0.003,0.004,0.005,0.008,0.011,0.016,0.024,0.035,0.050,0.072,
        0.085,0.101,0.120,0.141,0.163,0.189,0.218,0.248,0.278,0.310,
        0.341,0.371,0.396,0.419,0.437,0.451,0.459,0.462,0.461,0.457,
        0.448,0.438,0.426,0.413,0.387,0.361,0.337,None,None
    ],
    1.0: [
        0.003,0.004,0.006,0.009,0.013,0.019,0.027,0.040,0.057,0.083,
        0.098,0.116,0.136,0.160,0.185,0.213,0.244,0.276,0.308,0.340,
        0.371,0.400,0.424,0.443,0.458,0.467,0.471,0.470,0.464,0.456,
        0.444,0.431,0.417,0.403,0.375,0.349,0.325,None,None
    ],
    1.6: [
        0.003,0.005,0.007,0.010,0.015,0.022,0.032,0.046,0.065,0.093,
        0.110,0.130,0.153,0.177,0.206,0.236,0.269,0.302,0.335,0.367,
        0.396,0.423,0.445,0.461,0.472,0.476,0.476,0.471,0.461,0.450,
        0.436,0.420,0.406,0.391,0.363,None,None,None,None
    ],
    4.0: [
        0.004,0.006,0.009,0.014,0.020,0.030,0.043,0.062,0.089,0.124,
        0.147,0.173,0.200,0.230,0.263,0.297,0.332,0.367,0.398,0.427,
        0.451,0.469,0.480,0.486,0.485,0.480,0.469,0.456,0.440,0.424,
        0.407,0.392,0.377,0.362,0.337,None,None,None,None
    ],
    10.0: [
        0.006,0.009,0.014,0.020,0.030,0.044,0.062,0.090,0.126,0.175,
        0.203,0.234,0.268,0.303,0.338,0.373,0.406,0.435,0.459,0.477,
        0.488,0.491,0.489,0.481,0.469,0.455,0.439,0.422,0.405,0.389,
        0.374,0.360,0.346,0.334,0.312,None,None,None,None
    ]
}

# Create DataFrame
df = pd.DataFrame(data, index=potential)
df.index.name = "Potential (mV)"

# Display table
print(df)

# Plot
plt.figure(figsize=(10,6))

for col in df.columns:
    plt.plot(df.index, df[col], marker='o', label=f'k_f/a = {col}')

plt.xlabel('Potential (mV)')
plt.ylabel('Current Function')
plt.title('Current Functions vs Potential')
plt.legend()
plt.grid(True)

plt.show()

"""
MAIN SIMULATOR CELL: CV_simulate_and_Mecsim.py

STEPS:

  1) Open Docker.
  2) Run the cell.
  3) Enter the parameters to generate a matching MECSim Master.inp, and title it.
  4) After generating the Master.inp go to your downloads folder where you have
  MECSim Docker, check for the title: MECSimDockerImage, and drag the generated
  Master.inp file into the input folder.
  5) Run this command in terminal (within Downloads, MECSimDockerImage):
  sh run_mecsim_auto.sh
  * If using Windows use this command in PowerShell: run_mecsim_auto.bat
  6) Output will save automatically and results will open.
  * If you want to keep a previous reaction output, save it to a sperate folder,
  current output overrides.

-> Supports an indefinite number of reactions and
optional EC (follow-up chemical reaction) steps

Usage note:
    Python cv_simulate_and_mecsim.py
"""

import math
import os
import warnings
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from dataclasses import dataclass
from typing import List, Tuple

warnings.filterwarnings("ignore")

# Physical constants
F = 96485.0    # C/mol
R = 8.314      # J/(mol*K)
T0 = 298.15    # K reference temperature (25 degC)

#Data classes (shared by simulator AND MECSim generator)

@dataclass
class HalfCellReaction:
    """One electrochemical half-reaction: O + n*e- <-> R"""
    name: str = "Rxn1"
    E0: float = 0.0        # formal potential (V) AT the simulation temperature
    n: int = 1              # electrons transferred
    ks: float = 1.0        # standard rate constant (cm/s); large -> reversible
    alpha: float = 0.5      # transfer coefficient
    C0: float = 1e-6        # bulk concentration of O (mol/cm^3)
    D_O: float = 1e-5       # diffusion coeff of O (cm^2/s)
    D_R: float = 1e-5       # diffusion coeff of R (cm^2/s)
    has_ec: bool = False    # optional follow-up chemical step R -> P
    kf_chem: float = 0.0
    kb_chem: float = 0.0
    # Only used by the MECSim generator if you want extra Nernst/Arrhenius
    # correction beyond the E0/ks already entered:
    dS_rxn: float = 0.0     #reaction entropy (J/mol/K); 0 = no extra E0 shift
    Ea: float = 0.0         #activation energy (J/mol); 0 = no extra ks scaling


@dataclass
class CVParameters:
    E_start: float = 0.5
    E_rev: float = -0.5
    E_end: float = 0.5
    nu: float = 0.1
    n_cycles: int = 1
    A: float = 1.0
    Ru: float = 0.0          # uncompensated resistance, ohms, - MECSim only
    T: float = T0            # temperature (K)
    n_pts_exp: int = 12      #time resolution, 2^N points

# Finite-difference CV simulator

def simulate_cv(rxn: HalfCellReaction, cv: CVParameters) -> Tuple[np.ndarray, np.ndarray]:
    fT = F / (R * cv.T)

    n_pts_per_cycle = 600
    n_pts = n_pts_per_cycle * cv.n_cycles

    E_pts_half = n_pts_per_cycle // 2
    E_fwd = np.linspace(cv.E_start, cv.E_rev, E_pts_half, endpoint=False)
    E_back = np.linspace(cv.E_rev, cv.E_end, n_pts_per_cycle - E_pts_half, endpoint=True)
    E_one_cycle = np.concatenate([E_fwd, E_back])
    E_all = np.tile(E_one_cycle, cv.n_cycles)
    E_all = E_all[:n_pts]

    t_total = (abs(cv.E_start - cv.E_rev) + abs(cv.E_rev - cv.E_end)) * cv.n_cycles / cv.nu
    dt = t_total / n_pts

    D = rxn.D_O
    delta_max = 6 * np.sqrt(D * t_total)
    Nx = 200
    dx = delta_max / Nx

    r = D * dt / dx**2
    if r > 0.5:
        Nx = int(np.ceil(np.sqrt(D * t_total / (0.4 * dx**2)))) + 1
        dx = delta_max / Nx

    C_O = np.ones(Nx + 1) * rxn.C0
    C_R = np.zeros(Nx + 1)

    alpha1 = rxn.D_O / dx
    beta1 = rxn.D_R / dx

    currents = np.zeros(n_pts)

    for k, Ek in enumerate(E_all):
        fwd = rxn.ks * np.exp(-rxn.alpha * rxn.n * fT * (Ek - rxn.E0))
        bwd = rxn.ks * np.exp((1 - rxn.alpha) * rxn.n * fT * (Ek - rxn.E0))

        denom = alpha1 * beta1 + alpha1 * bwd + fwd * beta1
        C_O0 = (alpha1 * C_O[1] * (beta1 + bwd) + bwd * beta1 * C_R[1]) / denom
        C_R0 = (beta1 * C_R[1] + fwd * C_O0) / (beta1 + bwd)
        C_O[0] = max(0.0, C_O0)
        C_R[0] = max(0.0, C_R0)

        j = rxn.D_O * (C_O[1] - C_O[0]) / dx
        currents[k] = rxn.n * F * cv.A * j

        r_O = rxn.D_O * dt / dx**2
        r_R = rxn.D_R * dt / dx**2
        C_O_new = C_O.copy()
        C_R_new = C_R.copy()
        C_O_new[1:-1] = C_O[1:-1] + r_O * (C_O[2:] - 2 * C_O[1:-1] + C_O[:-2])
        C_R_new[1:-1] = C_R[1:-1] + r_R * (C_R[2:] - 2 * C_R[1:-1] + C_R[:-2])
        C_O_new[-1] = rxn.C0
        C_R_new[-1] = 0.0
        if rxn.has_ec and rxn.kf_chem > 0:
            k_net = rxn.kf_chem - rxn.kb_chem
            C_R_new = C_R_new * np.exp(-k_net * dt)
            C_R_new = np.maximum(C_R_new, 0)
        C_O, C_R = C_O_new, C_R_new

    return E_all, currents


def simulate_multi_cv(reactions: List[HalfCellReaction], cv: CVParameters):
    all_E, all_I, all_labels = [], [], []
    for rxn in reactions:
        E, I = simulate_cv(rxn, cv)
        all_E.append(E)
        all_I.append(I)
        all_labels.append(rxn.name)
    I_total = sum(all_I)
    return all_E[0], all_I, I_total, all_labels
#Input helpers

def get_float(prompt, default):
    while True:
        s = input(f"  {prompt} [{default}]: ").strip()
        if s == "":
            return float(default)
        try:
            return float(s)
        except ValueError:
            print("    Please enter a number.")


def get_int(prompt, default, min_val=1):
    while True:
        s = input(f"  {prompt} [{default}]: ").strip()
        if s == "":
            return int(default)
        try:
            v = int(s)
            if v >= min_val:
                return v
            print(f"    Must be >= {min_val}.")
        except ValueError:
            print("    Please enter an integer.")


def get_bool(prompt, default=False):
    while True:
        s = input(f"  {prompt} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
        if s == "":
            return default
        if s in ("y", "yes"):
            return True
        if s in ("n", "no"):
            return False
        print("    Enter y or n.")


def input_reaction(idx: int, T: float) -> HalfCellReaction:
    print(f"\n  -- Half-Cell Reaction #{idx} (O + n*e- <-> R) --")
    name = input(f"  Name [Rxn{idx}]: ").strip() or f"Rxn{idx}"
    E0 = get_float(f"Formal potential E0 at {T:.2f} K (V)", 0.0)
    n = get_int("Electrons transferred n", 1)
    ks = get_float("Standard rate constant ks (cm/s; large -> reversible)", 1.0)
    alpha = get_float("Transfer coefficient alpha", 0.5)
    C0 = get_float("Bulk concentration C0 (mol/cm^3, e.g. 1e-6 = 1 mM)", 1e-6)
    D_O = get_float("Diffusion coeff D_O (cm^2/s)", 1e-5)
    D_R = get_float("Diffusion coeff D_R (cm^2/s)", 1e-5)

    dS_rxn = 0.0
    Ea = 0.0
    if abs(T - T0) > 0.1:
        print(f"  (T != {T0} K -- optional MECSim thermal correction terms)")
        dS_rxn = get_float("Reaction entropy dS_rxn (J/mol/K); 0 = none", 0.0)
        Ea = get_float("Activation energy Ea (J/mol); 0 = none", 0.0)

    has_ec = get_bool("Add following chemical reaction (EC mechanism)?", False)
    kf_chem = 0.0
    kb_chem = 0.0
    if has_ec:
        kf_chem = get_float("Forward chem rate kf (s^-1)", 10.0)
        kb_chem = get_float("Reverse chem rate kb (s^-1, 0=irreversible)", 0.0)

    return HalfCellReaction(
        name=name, E0=E0, n=n, ks=ks, alpha=alpha,
        C0=C0, D_O=D_O, D_R=D_R,
        has_ec=has_ec, kf_chem=kf_chem, kb_chem=kb_chem,
        dS_rxn=dS_rxn, Ea=Ea,
    )


def input_cv_params() -> CVParameters:
    print("\n-- CV Waveform Parameters --")
    T = get_float("Temperature (K)", T0)
    E_start = get_float("Start potential E_start (V)", 0.5)
    E_rev = get_float("Reversal potential E_rev (V)", -0.5)
    E_end = get_float("End potential E_end (V)", E_start)
    nu = get_float("Scan rate v (V/s)", 0.1)
    n_cycles = get_int("Number of cycles", 1)
    A = get_float("Electrode area A (cm^2)", 1.0)
    Ru = get_float("Uncompensated resistance Ru (ohm, MECSim only)", 0.0)
    n_pts_exp = get_int("MECSim time resolution as 2^N points (N=12 -> 4096)", 12, min_val=8)
    return CVParameters(E_start=E_start, E_rev=E_rev, E_end=E_end,
                         nu=nu, n_cycles=n_cycles, A=A, Ru=Ru,
                         T=T, n_pts_exp=n_pts_exp)
#Plotting

COLORS = ["#2563EB", "#DC2626", "#16A34A", "#9333EA", "#EA580C",
          "#0891B2", "#B45309", "#BE185D", "#4F46E5", "#15803D"]


def plot_results(E, individual_I, I_total, labels, reactions, cv):
    n_rxn = len(individual_I)
    fig = plt.figure(figsize=(14, 9), facecolor="#0f172a")
    fig.suptitle("Cyclic Voltammetry Simulation", color="white",
                 fontsize=18, fontweight="bold", y=0.97)

    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.38,
                            left=0.08, right=0.97, top=0.91, bottom=0.08)

    ax_main = fig.add_subplot(gs[0, :])
    ax_ind = fig.add_subplot(gs[1, 0])
    ax_pot = fig.add_subplot(gs[1, 1])

    def style_ax(ax, title, xlabel, ylabel):
        ax.set_facecolor("#1e293b")
        ax.set_title(title, color="white", fontsize=12, pad=8)
        ax.set_xlabel(xlabel, color="#94a3b8", fontsize=10)
        ax.set_ylabel(ylabel, color="#94a3b8", fontsize=10)
        ax.tick_params(colors="#94a3b8", labelsize=9)
        for spine in ax.spines.values():
            spine.set_color("#334155")
        ax.grid(True, color="#1e3a5f", linewidth=0.5, alpha=0.8)

    style_ax(ax_main, "Total Cyclic Voltammogram", "Potential (V)", "Current (uA)")
    ax_main.plot(E, I_total * 1e6, color="#38bdf8", linewidth=2.2, label="Total current")
    i_max_idx = np.argmax(I_total)
    i_min_idx = np.argmin(I_total)
    ax_main.scatter(E[i_max_idx], I_total[i_max_idx] * 1e6, color="#fbbf24", zorder=5, s=80)
    ax_main.scatter(E[i_min_idx], I_total[i_min_idx] * 1e6, color="#f87171", zorder=5, s=80)
    ax_main.axhline(0, color="#475569", linewidth=0.8, linestyle="--")
    ax_main.annotate(f"  Epc={E[i_min_idx]:.3f} V\n  ipc={I_total[i_min_idx]*1e6:.2f} uA",
                      xy=(E[i_min_idx], I_total[i_min_idx] * 1e6),
                      xytext=(E[i_min_idx] + 0.05, I_total[i_min_idx] * 1e6 * 0.7),
                      color="#f87171", fontsize=8, arrowprops=dict(arrowstyle="->", color="#f87171"))
    ax_main.annotate(f"  Epa={E[i_max_idx]:.3f} V\n  ipa={I_total[i_max_idx]*1e6:.2f} uA",
                      xy=(E[i_max_idx], I_total[i_max_idx] * 1e6),
                      xytext=(E[i_max_idx] + 0.05, I_total[i_max_idx] * 1e6 * 0.7),
                      color="#fbbf24", fontsize=8, arrowprops=dict(arrowstyle="->", color="#fbbf24"))
    ax_main.legend(facecolor="#1e293b", labelcolor="white", fontsize=9)

    style_ax(ax_ind, "Individual Contributions", "Potential (V)", "Current (uA)")
    for idx, (I_rxn, lbl) in enumerate(zip(individual_I, labels)):
        col = COLORS[idx % len(COLORS)]
        rxn = reactions[idx]
        lbl_full = f"{lbl} (E0={rxn.E0:.2f}V"
        if rxn.has_ec:
            lbl_full += f", EC kf={rxn.kf_chem:.1g}s^-1"
        lbl_full += ")"
        ax_ind.plot(E, I_rxn * 1e6, color=col, linewidth=1.8, label=lbl_full)
    ax_ind.axhline(0, color="#475569", linewidth=0.8, linestyle="--")
    ax_ind.legend(facecolor="#1e293b", labelcolor="white", fontsize=7, loc="upper right")

    style_ax(ax_pot, "Applied Potential Waveform", "Point index", "Potential (V)")
    t_arr = np.linspace(0, len(E), len(E))
    ax_pot.plot(t_arr, E, color="#a78bfa", linewidth=1.6)
    ax_pot.axhline(cv.E_rev, color="#f87171", linewidth=0.8, linestyle=":",
                   label=f"E_rev = {cv.E_rev:.2f} V")
    ax_pot.axhline(cv.E_start, color="#fbbf24", linewidth=0.8, linestyle=":",
                   label=f"E_start = {cv.E_start:.2f} V")
    ax_pot.legend(facecolor="#1e293b", labelcolor="white", fontsize=8)

    info = (f"v = {cv.nu} V/s   |   T = {cv.T:.1f} K   |   "
            f"Cycles = {cv.n_cycles}   |   A = {cv.A} cm^2   |   Reactions = {n_rxn}")
    fig.text(0.5, 0.005, info, ha="center", color="#64748b", fontsize=9)

    plt.savefig("cv_simulation.png", dpi=150, bbox_inches="tight", facecolor="#0f172a")
    print("\n  Plot saved -> cv_simulation.png")
    plt.show()

# MECSim Master.inp generator
def adjust_E0_for_temperature(E0_ref, n, dS_rxn, T):
    if dS_rxn == 0.0:
        return E0_ref
    return E0_ref + (dS_rxn / (n * F)) * (T - T0)


def adjust_ks_for_temperature(ks_ref, Ea, T):
    if Ea == 0.0:
        return ks_ref
    return ks_ref * math.exp((-Ea / R) * (1.0 / T - 1.0 / T0))


def build_master_inp(reactions: List[HalfCellReaction], cv: CVParameters, outfile="Master.inp"):

    T = cv.T
    adjusted = []
    for rxn in reactions:
        E0_T = adjust_E0_for_temperature(rxn.E0, rxn.n, rxn.dS_rxn, T)
        ks_T = adjust_ks_for_temperature(rxn.ks, rxn.Ea, T)
        adjusted.append((E0_T, ks_T))

    species = []
    sp_labels = []
    for i, rxn in enumerate(reactions):
        species.append((rxn.C0, rxn.D_O, 0))
        species.append((0.0, rxn.D_R, 0))
        sp_labels.append(f"Ox_{i+1} ({rxn.name})")
        sp_labels.append(f"Red_{i+1} ({rxn.name})")

    ec_prod_idx = {}
    for i, rxn in enumerate(reactions):
        if rxn.has_ec:
            ec_prod_idx[i] = len(species)
            species.append((0.0, rxn.D_R, 0))
            sp_labels.append(f"Prod_{i+1} ({rxn.name}, EC product)")

    n_sp = len(species)

    rxn_lines = []
    for i, rxn in enumerate(reactions):
        E0_T, ks_T = adjusted[i]
        ox_idx = 2 * i
        red_idx = 2 * i + 1

        stoic = [0] * n_sp
        stoic[ox_idx] = -1
        stoic[red_idx] = rxn.n
        stoic_str = ", ".join(str(x) for x in stoic)
        line = (f"0, {stoic_str}, 0.0e0, 0.0e0, "
                f"{E0_T:.6f}, {ks_T:.4e}, {rxn.alpha:.4f}"
                f" ! CT: {rxn.name} (n={rxn.n}, E0={E0_T:.4f}V @{T:.1f}K, ks={ks_T:.3e})")
        rxn_lines.append(line)

        if rxn.has_ec:
            prod_idx = ec_prod_idx[i]
            stoic_c = [0] * n_sp
            stoic_c[red_idx] = -1
            stoic_c[prod_idx] = 1
            stoic_c_str = ", ".join(str(x) for x in stoic_c)
            line_c = (f"1, {stoic_c_str}, {rxn.kf_chem:.4e}, {rxn.kb_chem:.4e}, "
                      f"0.0, 1.0, 0.5"
                      f" ! Chem: Red_{i+1} -> Prod_{i+1} (kf={rxn.kf_chem}, kb={rxn.kb_chem})")
            rxn_lines.append(line_c)

    lines = []

    def w(s=""):
        lines.append(s)

    w(f"{T:.2f} ! Temperature (K)")
    w(f"{cv.Ru:.4e} ! uncompensated resistance (ohms)")
    w(f"{cv.E_start:.4f} ! E_start (V)")
    w(f"{cv.E_rev:.4f} ! E_rev (V)")
    w(f"{cv.n_cycles} ! number of cycles")
    w(f"{cv.nu:.4e} ! scan speed (V/s)")
    w(f"{cv.n_pts_exp} ! 2**X points in time across n cycles (int)")
    w("0 ! correct vscan and freq for DigiPot/FFT (0=no)")
    w("1 ! output type: 0=E,i,t; 1=DigiPot compatible")
    w("0 ! EC type: 0=Butler-Volmer, 1=Marcus theory")
    w("0 ! Pre-equilibrium switch: 0=stay with user entered")
    w("0 ! fix number of timesteps (1=yes)")
    w("4000 ! number of points (not 2^N, used if above=1)")
    w("0.10 ! beta (exponential grid coefficient)")
    w("10.0 ! Dstar_min")
    w("0.005e0 ! max voltage step")
    w("25.6e0 ! time resolution (us)")
    w("0 ! show extra output files (1=yes; 0=no)")
    w("0 ! use advanced voltage ramp (0=E_start=E_end)")
    w("2 ! number of E_rev lines for advanced ramp")
    w("0.0 ! E_start advanced")
    w("0.0 ! E_end advanced")
    w(f"{cv.E_start:.4f} ! E_rev 1")
    w(f"{cv.E_rev:.4f} ! E_rev 2")
    w("1 ! Geometry: 1=planar, 2=spherical, 3=cylinder, 4=RDE")
    w(f"{cv.A:.4e} ! Planar: surface area (cm^2)")
    w("1.0e0 ! Number of spheres")
    w("1.0e-4 ! Radius of sphere (cm)")
    w("0.50e0 ! Number of cylinders")
    w("0.001e0 ! Radius of cylinder (cm)")
    w("0.10e0 ! Length of cylinder (cm)")
    w("100.0 ! Spatial Resolution")
    w("1.0e-1 ! RDE radius (cm)")
    w("1.0e2 ! RDE rotation speed (rad/s)")
    w("1.0e-5 ! RDE kinematic viscosity (cm^2/s)")
    w("1 ! number of AC sources")
    w("0.0e0, 18.0e0 ! AC: amp (mV), freq (Hz) -- zero amp = DC only")
    w(f"{n_sp} ! number of species")
    for j, (C0, D, sc) in enumerate(species):
        w(f"{C0:.4e}, {D:.4e}, {sc} ! {sp_labels[j]}")
    w("4 ! capacitance polynomial order")
    w("0.0e0 ! Epzc (V)")
    w("0.0e0 ! a_0 (F/cm^2) -- double layer capacitance")
    w("0.0e0 ! a_1")
    w("0.0e0 ! a_2")
    w("0.0e0 ! a_3")
    w("0.0e0 ! a_4")
    for rline in rxn_lines:
        w(rline)
    w("")

    content = "\n".join(lines)
    with open(outfile, "w") as f:
        f.write(content)
    return content

# Main pipeline

def main():
    print("=" * 62)
    print("  CV Simulator + MECSim Master.inp Generator (combined)")
    print("  Enter your reactions ONCE -- get plots AND Master.inp")
    print("=" * 62)

    print("\n[Step 1] First half-cell reaction (required):")
    cv = input_cv_params()

    reactions: List[HalfCellReaction] = []
    reactions.append(input_reaction(1, cv.T))

    idx = 2
    while True:
        if get_bool(f"\n  Add another reaction (#{idx})?", False):
            reactions.append(input_reaction(idx, cv.T))
            idx += 1
        else:
            break

    #Run the simulation
    print(f"\n  Running simulation for {len(reactions)} reaction(s)...")
    E, individual_I, I_total, labels = simulate_multi_cv(reactions, cv)
    print("  Done.")

    print("\n-- Peak Summary --")
    i_pa = np.max(I_total)
    i_pc = np.min(I_total)
    E_pa = E[np.argmax(I_total)]
    E_pc = E[np.argmin(I_total)]
    print(f"  Epa = {E_pa:.4f} V   ipa = {i_pa*1e6:.4f} uA")
    print(f"  Epc = {E_pc:.4f} V   ipc = {i_pc*1e6:.4f} uA")
    if abs(i_pc) > 0:
        print(f"  |ipa/ipc| = {abs(i_pa/i_pc):.3f}  (1.0 -> reversible)")
    if abs(E_pa - E_pc) > 0:
        print(f"  dEp = {abs(E_pa-E_pc)*1000:.1f} mV  (59/n mV -> reversible)")

    plot_results(E, individual_I, I_total, labels, reactions, cv)

    fname = "cv_data.csv"
    header = "E_V," + ",".join([f"I_{l}_A" for l in labels]) + ",I_total_A"
    data = np.column_stack([E] + individual_I + [I_total])
    np.savetxt(fname, data, delimiter=",", header=header, comments="")
    print(f"  Saved -> {fname}")

    #Generates MECSim Master.inp from the same reactions/cv
    print("\n-- MECSim Master.inp Generation --")
    outfile = input("  Output filename [Master.inp]: ").strip() or "Master.inp"
    content = build_master_inp(reactions, cv, outfile=outfile)
    print(f"\n  Written -> {os.path.abspath(outfile)}")
    print("\n  Next steps:")
    print(f"  1. Copy {outfile} to the same folder as your MECSim executable")
    print("  2. Rename it to Master.inp if needed")
    print("  3. Run MECSim -> output appears in MECSimOutput.txt")


if __name__ == "__main__":
    main()
